# Generated by Django 6.1.1 on 2026-10-02 13:25

import common.const
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0004_auto_20230724_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='grade',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S015'), default='01', max_length=2, verbose_name='position grade'),
        ),
        migrations.AlterField(
            model_name='position',
            name='series',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S014'), default='A', max_length=1, verbose_name='position series'),
        ),
    ]
