# Generated by Django 6.1.1 on 2026-10-02 13:25

import basedata.models
import common.const
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0004_auto_20230724_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=functools.partial(basedata.models.load_value_list, 'S011'), default='01', max_length=2, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='business_domain',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S045'), default='OT', max_length=4, verbose_name='business domain'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S037'), default='4', max_length=2, null=True, verbose_name='major degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_type',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S035'), default='1', max_length=2, verbose_name='edu type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S018'), default='21', max_length=2, null=True, verbose_name='employ category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S022'), default='CN', max_length=2, null=True, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S037'), default='4', max_length=2, null=True, verbose_name='major degree'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'gender'), default='1', max_length=2, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='health',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S043'), default='1', max_length=2, null=True, verbose_name='health'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='literacy',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S024'), default='10', max_length=2, null=True, verbose_name='literacy'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='major',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S038'), default='99', max_length=2, null=True, verbose_name='major type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S023'), default='10', max_length=2, null=True, verbose_name='marital status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nation',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S021'), default='01', max_length=2, null=True, verbose_name='nation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='party',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S026'), default='13', max_length=2, null=True, verbose_name='political party'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S017'), default='00', max_length=2, verbose_name='employee rank'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S020'), default='00', max_length=2, null=True, verbose_name='religion'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='spjob',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S042'), default='00', max_length=2, null=True, verbose_name='special job'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S016'), default='10', max_length=2, null=True, verbose_name='employ status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag1',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S039'), default='99', max_length=2, null=True, verbose_name='tag1 fzjr'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag2',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S040'), default='9', max_length=2, null=True, verbose_name='tag2 dwld'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag3',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S041'), default='00', max_length=10, null=True, verbose_name='tag3 dsjs'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag4',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S027'), default='0', max_length=2, null=True, verbose_name='tag4 byzk'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ygxs',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S019'), default='2', max_length=2, null=True, verbose_name='employ ygxs'),
        ),
        migrations.AlterField(
            model_name='family',
            name='relation',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S025'), max_length=2, null=True, verbose_name='family title'),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S029'), default='17', max_length=2, null=True, verbose_name='social status'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tp',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S054'), default='10', max_length=2, null=True, verbose_name='mt type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_type',
            field=models.CharField(blank=True, choices=functools.partial(basedata.models.load_value_list, 'S013'), default='00', max_length=2, null=True, verbose_name='project type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=functools.partial(basedata.models.load_value_list, 'S012'), default='00', max_length=2, null=True, verbose_name='status'),
        ),
    ]
