# Generated by Django 6.1.1 on 2026-10-03 16:36

from django.db import migrations, models


def fill_identity_codes(apps, schema_editor):
    Employee = apps.get_model('basedata', 'Employee')
    Material = apps.get_model('basedata', 'Material')
    for row in Employee.objects.all():
        if not row.qr_token:
            row.qr_token = 'EM%05d' % row.pk
            row.save(update_fields=['qr_token'])
    for row in Material.objects.all():
        if not row.qr_token:
            row.qr_token = 'MT%05d' % row.pk
            row.save(update_fields=['qr_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0005_choices_lazy'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='face/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qr_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='二维码'),
        ),
        migrations.AddField(
            model_name='material',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='material/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='material',
            name='qr_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='二维码'),
        ),
        migrations.AddField(
            model_name='material',
            name='supply_kind',
            field=models.CharField(blank=True, choices=[('raw', '原材料'), ('hardware', '五金'), ('cutter', '刀具'), ('tool', '工具'), ('aux', '辅料'), ('part', '加工件')], default='', max_length=12, verbose_name='物料类别'),
        ),
        migrations.RunPython(fill_identity_codes, migrations.RunPython.noop),
    ]
