# Generated by Django 6.1.1 on 2026-10-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0006_employee_photo_employee_qr_token_material_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='drawing_file',
            field=models.FileField(blank=True, help_text='图片、PDF、DWG 或 DXF', null=True, upload_to='material/drawing/', verbose_name='二维图纸'),
        ),
        migrations.AddField(
            model_name='material',
            name='model_file',
            field=models.FileField(blank=True, help_text='STEP、IGES、STL 等', null=True, upload_to='material/model/', verbose_name='三维模型'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='face/', verbose_name='人脸照片'),
        ),
        migrations.AlterField(
            model_name='material',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='material/', verbose_name='物料照片'),
        ),
    ]
