# Generated by Django 6.1.1 on 2026-10-03 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='单据')),
                ('token', models.CharField(max_length=40, unique=True, verbose_name='二维码')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='单据类型')),
            ],
            options={
                'verbose_name': '单据二维码',
                'verbose_name_plural': '单据二维码',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
