# Generated by Django 6.1.1 on 2026-10-03 11:13

import common.generic
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0002_doclink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='编号')),
                ('qr_token', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='二维码')),
                ('name', models.CharField(max_length=40, verbose_name='区域')),
                ('seq', models.PositiveIntegerField(default=10, verbose_name='顺序')),
                ('machine_types', models.CharField(blank=True, default='', max_length=80, verbose_name='承接设备类型')),
                ('note', models.CharField(blank=True, default='', max_length=120, verbose_name='说明')),
            ],
            options={
                'verbose_name': '车间区域',
                'verbose_name_plural': '车间区域',
                'ordering': ['seq', 'id'],
            },
            bases=(common.generic.ToStringMixin, models.Model),
        ),
        migrations.AddField(
            model_name='machine',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='cnc.shoparea', verbose_name='所在区域'),
        ),
    ]
