# Generated by Django 6.1.1 on 2026-10-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0003_shop_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('MC', '加工中心'), ('LATHE', '车床'), ('MILL', '铣床'), ('GRIND', '磨床'), ('DRILL', '钻床'), ('WIRE', '线切割'), ('EDM', '电火花'), ('SAW', '锯床'), ('BENCH', '钳工'), ('ASSEM', '装配'), ('QC', '检验'), ('PACK', '包装'), ('OUT', '外协')], default='MC', max_length=10, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='process',
            name='machine_type',
            field=models.CharField(choices=[('MC', '加工中心'), ('LATHE', '车床'), ('MILL', '铣床'), ('GRIND', '磨床'), ('DRILL', '钻床'), ('WIRE', '线切割'), ('EDM', '电火花'), ('SAW', '锯床'), ('BENCH', '钳工'), ('ASSEM', '装配'), ('QC', '检验'), ('PACK', '包装'), ('OUT', '外协')], default='MC', max_length=10, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='routingstep',
            name='machine_type',
            field=models.CharField(choices=[('MC', '加工中心'), ('LATHE', '车床'), ('MILL', '铣床'), ('GRIND', '磨床'), ('DRILL', '钻床'), ('WIRE', '线切割'), ('EDM', '电火花'), ('SAW', '锯床'), ('BENCH', '钳工'), ('ASSEM', '装配'), ('QC', '检验'), ('PACK', '包装'), ('OUT', '外协')], default='MC', max_length=10, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='workoperation',
            name='machine_type',
            field=models.CharField(choices=[('MC', '加工中心'), ('LATHE', '车床'), ('MILL', '铣床'), ('GRIND', '磨床'), ('DRILL', '钻床'), ('WIRE', '线切割'), ('EDM', '电火花'), ('SAW', '锯床'), ('BENCH', '钳工'), ('ASSEM', '装配'), ('QC', '检验'), ('PACK', '包装'), ('OUT', '外协')], default='MC', max_length=10, verbose_name='设备类型'),
        ),
    ]
