# Generated by Django 6.1.1 on 2026-10-03 11:50

import common.generic
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0005_choices_lazy'),
        ('cnc', '0004_assembly_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyBom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='编号')),
                ('qr_token', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='二维码')),
                ('name', models.CharField(max_length=80, verbose_name='BOM名称')),
                ('version', models.CharField(default='A', max_length=20, verbose_name='版本')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assembly_boms', to='basedata.material', verbose_name='总成物料')),
            ],
            options={
                'verbose_name': '部件装配BOM',
                'verbose_name_plural': '部件装配BOM',
                'ordering': ['-id'],
            },
            bases=(common.generic.ToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssemblyBomLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=10, verbose_name='顺序')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='单套用量')),
                ('critical', models.BooleanField(default=False, verbose_name='关键件')),
                ('note', models.CharField(blank=True, default='', max_length=120, verbose_name='说明')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cnc.assemblybom', verbose_name='BOM')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedata.material', verbose_name='零件')),
            ],
            options={
                'verbose_name': 'BOM明细',
                'verbose_name_plural': 'BOM明细',
                'ordering': ['seq', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='编号')),
                ('qr_token', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='二维码')),
                ('title', models.CharField(max_length=80, verbose_name='装配任务')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='套数')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='交期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('kitting', '待配料'), ('assembling', '装配中'), ('qc', '待检'), ('done', '已完工'), ('cancelled', '已取消')], default='draft', max_length=12, verbose_name='状态')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='下达时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完工时间')),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cnc.assemblybom', verbose_name='装配BOM')),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'C'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='basedata.partner', verbose_name='客户')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assembly_orders', to='basedata.material', verbose_name='总成物料')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnc.machine', verbose_name='装配工位')),
            ],
            options={
                'verbose_name': '部件装配工单',
                'verbose_name_plural': '部件装配工单',
                'ordering': ['-id'],
            },
            bases=(common.generic.ToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssemblyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=10, verbose_name='顺序')),
                ('per_qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='单套用量')),
                ('need_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='需求数量')),
                ('issued_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='已配数量')),
                ('lot_no', models.CharField(blank=True, default='', max_length=40, verbose_name='批次')),
                ('critical', models.BooleanField(default=False, verbose_name='关键件')),
                ('status', models.CharField(choices=[('wait', '待配'), ('partial', '部分配料'), ('issued', '已齐')], default='wait', max_length=12, verbose_name='状态')),
                ('note', models.CharField(blank=True, default='', max_length=120, verbose_name='说明')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedata.material', verbose_name='零件')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='cnc.assemblyorder', verbose_name='装配工单')),
            ],
            options={
                'verbose_name': '部件装配配料',
                'verbose_name_plural': '部件装配配料',
                'ordering': ['seq', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='编号')),
                ('qr_token', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='二维码')),
                ('seq', models.PositiveIntegerField(default=1, verbose_name='套次')),
                ('status', models.CharField(choices=[('wait', '待装'), ('running', '装配中'), ('qc', '待检'), ('pass', '合格'), ('fail', '不合格')], default='wait', max_length=12, verbose_name='状态')),
                ('result', models.CharField(blank=True, choices=[('', '未检'), ('pass', '合格'), ('fail', '不合格'), ('concession', '让步接收')], default='', max_length=12, verbose_name='检验结论')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开工时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='装完时间')),
                ('assembler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='装配员')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='cnc.assemblyorder', verbose_name='装配工单')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnc.machine', verbose_name='工位')),
            ],
            options={
                'verbose_name': '部件装配单件',
                'verbose_name_plural': '部件装配单件',
                'ordering': ['order', 'seq', 'id'],
            },
            bases=(common.generic.ToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssemblyFit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(blank=True, default='', max_length=40, verbose_name='批次')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='数量')),
                ('note', models.CharField(blank=True, default='', max_length=120, verbose_name='说明')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedata.material', verbose_name='零件')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fits', to='cnc.assemblyunit', verbose_name='单件')),
            ],
            options={
                'verbose_name': '装入记录',
                'verbose_name_plural': '装入记录',
                'ordering': ['id'],
            },
        ),
    ]
