# Generated by Django 6.1.1 on 2026-10-03 12:11

import common.generic
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0005_assembly'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoperation',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnc.ncprogram', verbose_name='数控程序'),
        ),
        migrations.AddField(
            model_name='workoperation',
            name='setup_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='调机说明'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('MC', '加工中心'), ('LATHE', '车床'), ('MILL', '铣床'), ('GRIND', '磨床'), ('DRILL', '钻床'), ('WIRE', '线切割'), ('EDM', '电火花'), ('SAW', '锯床'), ('BENCH', '钳工'), ('ASSEM', '装配'), ('PROG', '编程'), ('SETUP', '调机'), ('MANUAL', '手动设备'), ('QC', '检验'), ('PACK', '包装'), ('OUT', '外协')], default='MC', max_length=10, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='process',
            name='machine_type',
            field=models.CharField(choices=[('MC', '加工中心'), ('LATHE', '车床'), ('MILL', '铣床'), ('GRIND', '磨床'), ('DRILL', '钻床'), ('WIRE', '线切割'), ('EDM', '电火花'), ('SAW', '锯床'), ('BENCH', '钳工'), ('ASSEM', '装配'), ('PROG', '编程'), ('SETUP', '调机'), ('MANUAL', '手动设备'), ('QC', '检验'), ('PACK', '包装'), ('OUT', '外协')], default='MC', max_length=10, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='routingstep',
            name='machine_type',
            field=models.CharField(choices=[('MC', '加工中心'), ('LATHE', '车床'), ('MILL', '铣床'), ('GRIND', '磨床'), ('DRILL', '钻床'), ('WIRE', '线切割'), ('EDM', '电火花'), ('SAW', '锯床'), ('BENCH', '钳工'), ('ASSEM', '装配'), ('PROG', '编程'), ('SETUP', '调机'), ('MANUAL', '手动设备'), ('QC', '检验'), ('PACK', '包装'), ('OUT', '外协')], default='MC', max_length=10, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='workoperation',
            name='machine_type',
            field=models.CharField(choices=[('MC', '加工中心'), ('LATHE', '车床'), ('MILL', '铣床'), ('GRIND', '磨床'), ('DRILL', '钻床'), ('WIRE', '线切割'), ('EDM', '电火花'), ('SAW', '锯床'), ('BENCH', '钳工'), ('ASSEM', '装配'), ('PROG', '编程'), ('SETUP', '调机'), ('MANUAL', '手动设备'), ('QC', '检验'), ('PACK', '包装'), ('OUT', '外协')], default='MC', max_length=10, verbose_name='设备类型'),
        ),
        migrations.CreateModel(
            name='MaintainOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='编号')),
                ('qr_token', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='二维码')),
                ('kind', models.CharField(choices=[('repair', '维修'), ('maintain', '保养')], default='repair', max_length=12, verbose_name='类型')),
                ('title', models.CharField(max_length=80, verbose_name='项目')),
                ('symptom', models.CharField(blank=True, default='', max_length=200, verbose_name='现象')),
                ('status', models.CharField(choices=[('open', '待处理'), ('doing', '进行中'), ('done', '已完成'), ('cancelled', '已取消')], default='open', max_length=12, verbose_name='状态')),
                ('plan_date', models.DateField(blank=True, null=True, verbose_name='计划日期')),
                ('work_done', models.CharField(blank=True, default='', max_length=200, verbose_name='处理内容')),
                ('spare', models.CharField(blank=True, default='', max_length=120, verbose_name='更换备件')),
                ('note', models.CharField(blank=True, default='', max_length=120, verbose_name='说明')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开工时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完工时间')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cnc.machine', verbose_name='设备')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='维修人')),
            ],
            options={
                'verbose_name': '设备维修保养',
                'verbose_name_plural': '设备维修保养',
                'ordering': ['-id'],
            },
            bases=(common.generic.ToStringMixin, models.Model),
        ),
    ]
