# Generated by Django 6.1.1 on 2026-10-03 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0006_maintain_and_processes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblybom',
            options={'ordering': ['-id'], 'verbose_name': '部件装配清单', 'verbose_name_plural': '部件装配清单'},
        ),
        migrations.AlterModelOptions(
            name='assemblybomline',
            options={'ordering': ['seq', 'id'], 'verbose_name': '清单明细', 'verbose_name_plural': '清单明细'},
        ),
        migrations.AlterField(
            model_name='assemblybom',
            name='name',
            field=models.CharField(max_length=80, verbose_name='清单名称'),
        ),
        migrations.AlterField(
            model_name='assemblybomline',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cnc.assemblybom', verbose_name='装配清单'),
        ),
        migrations.AlterField(
            model_name='assemblyorder',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cnc.assemblybom', verbose_name='装配清单'),
        ),
    ]
