# Generated by Django 6.1.1 on 2026-10-03 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0006_employee_photo_employee_qr_token_material_photo_and_more'),
        ('cnc', '0007_alter_assemblybom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='cnc/model/', verbose_name='三维模型'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='cnc/drawing/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='cnc/fixture/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='machine',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='cnc/machine/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='tool',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='cnc/tool/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='drawing_file',
            field=models.FileField(blank=True, null=True, upload_to='cnc/drawing/', verbose_name='二维图纸'),
        ),
        migrations.CreateModel(
            name='FaceSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='face/', verbose_name='人脸照片')),
                ('feature', models.TextField(verbose_name='特征')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='basedata.employee', verbose_name='职员')),
            ],
            options={
                'verbose_name': '人脸',
                'verbose_name_plural': '人脸',
                'ordering': ['-id'],
            },
        ),
    ]
