# Generated by Django 6.1.1 on 2026-10-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0007_material_drawing_file_material_model_file_and_more'),
        ('cnc', '0008_drawing_model_file_drawing_photo_fixture_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facesample',
            name='origin',
            field=models.CharField(blank=True, default='train', max_length=12, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='facesample',
            name='feature',
            field=models.TextField(blank=True, default='', verbose_name='特征'),
        ),
        migrations.CreateModel(
            name='ObjectSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='object/', verbose_name='物体照片')),
                ('feature', models.TextField(blank=True, default='', verbose_name='特征')),
                ('origin', models.CharField(blank=True, default='train', max_length=12, verbose_name='来源')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_samples', to='basedata.material', verbose_name='物料')),
            ],
            options={
                'verbose_name': '物体样本',
                'verbose_name_plural': '物体样本',
                'ordering': ['-id'],
            },
        ),
    ]
