# Generated by Django 6.1.1 on 2026-10-03 14:27

import common.generic
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_runtime(apps, schema_editor):
    FileServer = apps.get_model('syscfg', 'FileServer')
    DatabaseServer = apps.get_model('syscfg', 'DatabaseServer')
    BackupPlan = apps.get_model('syscfg', 'BackupPlan')
    if not FileServer.objects.exists():
        FileServer.objects.create(
            name='文件服务器',
            kind='share',
            enabled=False,
            note='填写局域网地址和共享名，测试写入成功后再启用。未启用时文件仍在本机 upload 目录。',
        )
    if not DatabaseServer.objects.exists():
        from django.conf import settings
        db = settings.DATABASES['default']
        DatabaseServer.objects.create(
            name='当前数据库',
            host=db.get('HOST') or '127.0.0.1',
            port=int(db.get('PORT') or 3306),
            db_name=db.get('NAME') or '',
            user=db.get('USER') or '',
            password=db.get('PASSWORD') or '',
            startup=False,
            note='这是正在使用的数据库。勾选下次启动并重启服务后才会改连。',
        )
    if not BackupPlan.objects.exists():
        BackupPlan.objects.create(
            name='每日备份',
            include_database=True,
            include_files=True,
            keep_count=7,
            run_hour=2,
            enabled=False,
            note='可立即备份。每天自动执行请在本机计划任务中运行 manage.py run_backup。',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('syscfg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名称')),
                ('include_database', models.BooleanField(default=True, verbose_name='备份数据库')),
                ('include_files', models.BooleanField(default=True, verbose_name='备份文件')),
                ('backup_dir', models.CharField(blank=True, default='', help_text='留空则使用文件服务器下的「备份」文件夹', max_length=200, verbose_name='备份目录')),
                ('keep_count', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='保留份数')),
                ('run_hour', models.PositiveSmallIntegerField(default=2, help_text='0 到 23。到点执行需要在这台电脑建立计划任务，运行 manage.py run_backup', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='每天几点')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='最近备份')),
                ('last_status', models.CharField(blank=True, choices=[('', '未执行'), ('ok', '成功'), ('fail', '失败')], default='', max_length=10, verbose_name='最近结果')),
                ('last_message', models.CharField(blank=True, default='', max_length=200, verbose_name='最近说明')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': '备份方案',
                'verbose_name_plural': '备份方案',
            },
            bases=(common.generic.ToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DatabaseServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名称')),
                ('host', models.CharField(default='127.0.0.1', max_length=80, verbose_name='服务器地址')),
                ('port', models.PositiveIntegerField(default=3306, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='端口')),
                ('db_name', models.CharField(max_length=64, verbose_name='数据库名')),
                ('user', models.CharField(max_length=40, verbose_name='账号')),
                ('password', models.CharField(blank=True, default='', max_length=80, verbose_name='密码')),
                ('startup', models.BooleanField(default=False, help_text='勾选并保存后写入启动配置，重启服务才生效', verbose_name='下次启动使用')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='最近检测')),
                ('last_message', models.CharField(blank=True, default='', max_length=200, verbose_name='检测结果')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': '数据库',
                'verbose_name_plural': '数据库',
            },
            bases=(common.generic.ToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FileServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名称')),
                ('kind', models.CharField(choices=[('local', '本机目录'), ('share', '局域网共享')], default='share', max_length=10, verbose_name='类型')),
                ('host', models.CharField(blank=True, default='', help_text='局域网地址，例如 192.168.1.20', max_length=80, verbose_name='服务器地址')),
                ('share', models.CharField(blank=True, default='', help_text='文件服务器上已共享的文件夹名', max_length=80, verbose_name='共享名')),
                ('directory', models.CharField(blank=True, default='', help_text='共享下的子目录。本机目录则填写完整路径，留空表示本机 upload', max_length=200, verbose_name='目录')),
                ('username', models.CharField(blank=True, default='', help_text='留空则使用当前 Windows 登录账号', max_length=40, verbose_name='访问账号')),
                ('password', models.CharField(blank=True, default='', max_length=80, verbose_name='访问密码')),
                ('enabled', models.BooleanField(default=False, help_text='启用后，新上传的文件写入这里。请先测试写入。', verbose_name='启用')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='最近检测')),
                ('last_message', models.CharField(blank=True, default='', max_length=200, verbose_name='检测结果')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': '文件服务器',
                'verbose_name_plural': '文件服务器',
            },
            bases=(common.generic.ToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('ok', '成功'), ('fail', '失败')], default='fail', max_length=10, verbose_name='结果')),
                ('path', models.CharField(blank=True, default='', max_length=400, verbose_name='备份位置')),
                ('message', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syscfg.backupplan', verbose_name='备份方案')),
            ],
            options={
                'verbose_name': '备份记录',
                'verbose_name_plural': '备份记录',
                'ordering': ['-id'],
            },
            bases=(common.generic.ToStringMixin, models.Model),
        ),
        migrations.AddField(
            model_name='backupplan',
            name='file_server',
            field=models.ForeignKey(blank=True, help_text='留空则备份到本机 backup 目录', null=True, on_delete=django.db.models.deletion.SET_NULL, to='syscfg.fileserver', verbose_name='存放位置'),
        ),
        migrations.RunPython(seed_runtime, migrations.RunPython.noop),
    ]
