# Generated by Django 6.1.1 on 2026-10-02 13:25

import common.const
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20230724_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitem',
            name='tax',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S052'), default='0.00', max_length=6, verbose_name='tax rate'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('00', 'NEW'), ('01', 'IN PROGRESS'), ('04', 'DROP'), ('09', 'APPROVED'), ('99', 'ALREADY STOCK IN')], default='00', max_length=2, verbose_name='status'),
        ),
    ]
