# Generated by Django 6.1.1 on 2026-10-02 13:25

import common.const
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20230724_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalaryitem',
            name='calculate_way',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S050'), default='10', max_length=2, verbose_name='calculate way'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S018'), default='21', max_length=2, null=True, verbose_name='employ category'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='gender',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'gender'), default='1', max_length=2, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='probation_months',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S047'), default='3', max_length=2, verbose_name='probation months'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rank',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S017'), default='00', max_length=2, verbose_name='employee rank'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ygxs',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S019'), default='2', max_length=2, null=True, verbose_name='employ ygxs'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='classification',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S048'), default='10', max_length=2, verbose_name='classification'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='plus_or_minus',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S049'), default='+', max_length=2, verbose_name='plus or minus'),
        ),
    ]
