# Generated by Django 6.1.1 on 2026-10-03 14:49

import common.generic
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basedata', '0005_choices_lazy'),
        ('cnc', '0007_alter_assemblybom_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('incoming', '来料检验'), ('first', '首件检验'), ('patrol', '巡检'), ('process', '工序检验'), ('outsource', '外协回厂检验'), ('assembly', '装配检验'), ('final', '终检'), ('ship', '出货检验')], max_length=12, verbose_name='环节')),
                ('process_name', models.CharField(blank=True, default='', help_text='留空表示这个环节都要检。填写后只针对同名工序', max_length=40, verbose_name='工序名称')),
                ('required', models.BooleanField(default=True, help_text='工单、批次、外协和装配页面会标出还没完成的必检', verbose_name='必检')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': '质量控制点',
                'verbose_name_plural': '质量控制点',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CheckRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='编号')),
                ('qr_token', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='二维码')),
                ('stage', models.CharField(choices=[('incoming', '来料检验'), ('first', '首件检验'), ('patrol', '巡检'), ('process', '工序检验'), ('outsource', '外协回厂检验'), ('assembly', '装配检验'), ('final', '终检'), ('ship', '出货检验')], default='process', max_length=12, verbose_name='环节')),
                ('check_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='检验数量')),
                ('fail_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='不合格数量')),
                ('result', models.CharField(choices=[('pending', '待判定'), ('pass', '合格'), ('fail', '不合格'), ('concession', '让步接收')], default='pending', max_length=12, verbose_name='结论')),
                ('disposition', models.CharField(blank=True, choices=[('', '未处置'), ('rework', '返工'), ('repair', '返修'), ('scrap', '报废'), ('concession', '让步接收'), ('isolate', '隔离')], default='', max_length=12, verbose_name='处置')),
                ('status', models.CharField(choices=[('open', '进行中'), ('closed', '已关闭')], default='open', max_length=12, verbose_name='状态')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('assembly_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='cnc.assemblyunit', verbose_name='装配单件')),
                ('inspection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_check', to='cnc.inspection', verbose_name='质检单')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='检验员')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='cnc.materiallot', verbose_name='物料批次')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='cnc.workoperation', verbose_name='工序')),
                ('outsource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='cnc.outsourceorder', verbose_name='外协单')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='cnc.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '检验记录',
                'verbose_name_plural': '检验记录',
                'ordering': ['-id'],
            },
            bases=(common.generic.ToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='数量')),
                ('reason', models.CharField(blank=True, choices=[('size', '尺寸超差'), ('setup', '装夹不当'), ('tool', '刀具崩刃'), ('program', '程序错误'), ('material', '材料缺陷'), ('other', '其他')], default='', max_length=20, verbose_name='原因')),
                ('disposition', models.CharField(blank=True, choices=[('', '未处置'), ('rework', '返工'), ('repair', '返修'), ('scrap', '报废'), ('concession', '让步接收'), ('isolate', '隔离')], default='', max_length=12, verbose_name='处置')),
                ('closed', models.BooleanField(default=False, verbose_name='已关闭')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='quality.checkrecord', verbose_name='检验记录')),
            ],
            options={
                'verbose_name': '不合格处置',
                'verbose_name_plural': '不合格处置',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=10, verbose_name='顺序')),
                ('name', models.CharField(max_length=60, verbose_name='项目')),
                ('nominal', models.CharField(blank=True, default='', max_length=40, verbose_name='公称值')),
                ('lower_limit', models.CharField(blank=True, default='', max_length=40, verbose_name='下限')),
                ('upper_limit', models.CharField(blank=True, default='', max_length=40, verbose_name='上限')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
                ('method', models.CharField(blank=True, default='', max_length=20, verbose_name='检验方法')),
                ('key_size', models.BooleanField(default=False, verbose_name='关键尺寸')),
                ('measured', models.CharField(blank=True, default='', max_length=40, verbose_name='实测')),
                ('result', models.CharField(blank=True, choices=[('', '未测'), ('pass', '合格'), ('fail', '不合格')], default='', max_length=12, verbose_name='判定')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='quality.checkrecord', verbose_name='检验记录')),
            ],
            options={
                'verbose_name': '实测',
                'verbose_name_plural': '实测',
                'ordering': ['record', 'seq', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='编号')),
                ('qr_token', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='二维码')),
                ('name', models.CharField(max_length=80, verbose_name='标准名称')),
                ('stage', models.CharField(choices=[('incoming', '来料检验'), ('first', '首件检验'), ('patrol', '巡检'), ('process', '工序检验'), ('outsource', '外协回厂检验'), ('assembly', '装配检验'), ('final', '终检'), ('ship', '出货检验')], default='process', max_length=12, verbose_name='环节')),
                ('process_name', models.CharField(blank=True, default='', max_length=40, verbose_name='工序名称')),
                ('version', models.CharField(default='A', max_length=20, verbose_name='版本')),
                ('active', models.BooleanField(default=True, verbose_name='在用')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('material', models.ForeignKey(blank=True, help_text='留空则作为该环节的通用标准', null=True, on_delete=django.db.models.deletion.PROTECT, to='basedata.material', verbose_name='物料')),
            ],
            options={
                'verbose_name': '检验标准',
                'verbose_name_plural': '检验标准',
                'ordering': ['-id'],
            },
            bases=(common.generic.ToStringMixin, models.Model),
        ),
        migrations.AddField(
            model_name='checkrecord',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.standard', verbose_name='检验标准'),
        ),
        migrations.CreateModel(
            name='StandardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=10, verbose_name='顺序')),
                ('name', models.CharField(max_length=60, verbose_name='项目')),
                ('nominal', models.CharField(blank=True, default='', max_length=40, verbose_name='公称值')),
                ('lower_limit', models.CharField(blank=True, default='', max_length=40, verbose_name='下限')),
                ('upper_limit', models.CharField(blank=True, default='', max_length=40, verbose_name='上限')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
                ('method', models.CharField(blank=True, default='', max_length=20, verbose_name='检验方法')),
                ('key_size', models.BooleanField(default=False, verbose_name='关键尺寸')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.standard', verbose_name='检验标准')),
            ],
            options={
                'verbose_name': '检验项目',
                'verbose_name_plural': '检验项目',
                'ordering': ['standard', 'seq', 'id'],
            },
        ),
    ]
