# Generated by Django 6.1.1 on 2026-10-02 13:25

import common.const
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20230724_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='tax',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S052'), default='0.00', max_length=6, verbose_name='tax rate'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tax',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S052'), default='0.00', max_length=6, verbose_name='tax rate'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='invoice_type',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S053'), default='10', max_length=6, verbose_name='invoice type'),
        ),
    ]
