# Generated by Django 6.1.1 on 2026-10-02 13:25

import common.const
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfhelp', '0004_auto_20230724_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='business_domain',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S045'), default='OT', max_length=4, verbose_name='business domain'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='classification',
            field=models.CharField(choices=functools.partial(common.const.load_value_list, 'S044'), default='D', max_length=4, verbose_name='classification'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(blank=True, choices=functools.partial(common.const.load_value_list, 'S046'), default='NEW', max_length=6, null=True, verbose_name='status'),
        ),
    ]
