# Generated by Django 6.1.1 on 2026-10-03 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0003_alter_modal_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modal',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['basedata', 'organ', 'purchase', 'sale', 'invent', 'selfhelp', 'hr', 'cnc']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type'),
        ),
    ]
