# Generated by Django 6.1.1 on 2026-10-03 13:20

import common.generic
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_workflow_document_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('arrive', '待处理'), ('finish', '已通过'), ('deny', '已拒绝'), ('stop', '已终止')], default='arrive', max_length=12, verbose_name='类型')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('body', models.CharField(blank=True, default='', max_length=200, verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='推送时间')),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.instance', verbose_name='workflow instance')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.node', verbose_name='workflow node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='handler')),
            ],
            options={
                'verbose_name': '流程推送',
                'verbose_name_plural': '流程推送',
                'ordering': ['-id'],
            },
            bases=(common.generic.ToStringMixin, models.Model),
        ),
    ]
